### ISSUE TITLE
[Bug]  TypeError: Object has been destroyed at Function.<anonymous> (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:72675)

### ISSUE THREAD

**Issue by stushep** [unknownskl/xbox-xcloud-client#1219]
### Describe the bug

Greenlight on MacBook Pro M1 (Sonoma) attempts to log into my MS account twice. First attempt is successful but the second attempt fails (both with a correct password and a correct MFA response). After this I get the following error:

A Javascript error occured in the main process
Uncaught Exception:
TypeError: Object has been destroyed
at Function.<anonymous> (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:72675)

I'm able to see that the console is active, can attempt to start a stream etc but the stream never connects.

### Expected behavior

Expected stream to load

### Environment

```markdown
- OS: MacOS Sonoma 14.0
- Device: MacBook Pro M1
- Greenlight version: 2.3.1
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by stushep** [comment]
Additionally, updated my MacBook Pro to Sonoma 14.4.1 to rule out the out of date OS. Issue persists.

<img width="248" alt="Screenshot 2024-05-05 at 09 01 02" src="https://github.com/unknownskl/greenlight/assets/65246976/430fe734-4675-497c-b14f-781a3801e9a7">
<img width="186" alt="Screenshot 2024-05-05 at 09 01 12" src="https://github.com/unknownskl/greenlight/assets/65246976/e0219718-6132-4ed4-bde4-c8eb2a728649">
