### ISSUE TITLE
`A JavaScript error occurred in the main process` when launching v2.0.0-beta5 

### ISSUE THREAD

**Issue by rakleed** [unknownskl/xbox-xcloud-client#777]
After updating to v2.0.0-beta5, when launching the application on macOS 13.2.1, the following error appears:

<details><summary>Log</summary>

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: node-loader:
Error: dlopen(/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr, 0x0001): tried: '/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr' (no such file), '/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/private/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr' (no such file), '/private/var/folders/yy/fl1nk2x57zx2bdsqykmp77lw0000gn/T/.com.unknownskl.greenlight.8ui2rr' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
at 2905 (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:71322)
at r (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:73464)
at /Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:74515
at /Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:102749
at Object.<anonymous> (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:102770)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at c._load (node:electron/js2c/asar_bundle:5:13343)
```

</details>

![Screenshot 2023-03-20 at 16 41 17](https://user-images.githubusercontent.com/19418601/226357423-49cf9829-3955-4d6a-bd3b-03e5f334908a.png)

**Comment by 3geekfamily** [comment]
I'm experiencing the same issue. It seems like the universal binary only has the x86/x64 version, and not ARM64.

**Comment by unknownskl** [comment]
I was already afraid for this. Thanks for reporting, will see what i can do on my side.

In the meantime, when you right click on the file and go to properties and run it using Rosetta, does the error still pops up? This will force the application to run in 86/64 bit mode

**Comment by rakleed** [comment]
> In the meantime, when you right click on the file and go to properties and run it using Rosetta, does the error still pops up?

If the app is forced to open using Rosetta, then the error does not occur.

**Comment by unknownskl** [comment]
Can you try this build? https://github.com/unknownskl/xbox-xcloud-client/actions/runs/4471413645

I don't have a Macbook with an Apple silicon so cannot try the build, let me know if this works for you :)

**Comment by 3geekfamily** [comment]
Confirmed, that one looks good! Launches without errors - no Rosetta needed.

**Comment by unknownskl** [comment]
Thnx for checking! beta 6 has been released
