### ISSUE TITLE
Missing dependencys for deb package

### ISSUE THREAD

**Issue by js-denton** [unknownskl/xbox-xcloud-client#814]
Hello. Current stable version 1.2.0 don't have depens libc in control file.
Neede add:
Depends: libc6 (>= 2.32)

Bette if downgrade libc. My distr based on debian 10 have libc 2.28

<details>
  <summary>stdout</summary>

  ```bash
  ○ → greenlight 
  A JavaScript error occurred in the main process
  Uncaught Exception:
  Error: node-loader:
  Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.cGJ5V8)
      at 2905 (/opt/Greenlight/resources/app.asar/app/background.js:1:71322)
      at r (/opt/Greenlight/resources/app.asar/app/background.js:1:73464)
      at /opt/Greenlight/resources/app.asar/app/background.js:1:74515
      at /opt/Greenlight/resources/app.asar/app/background.js:1:103510
      at Object.<anonymous> (/opt/Greenlight/resources/app.asar/app/background.js:1:103531)
      at Module._compile (node:internal/modules/cjs/loader:1120:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
      at Module.load (node:internal/modules/cjs/loader:988:32)
      at Module._load (node:internal/modules/cjs/loader:829:12)
      at c._load (node:electron/js2c/asar_bundle:5:13343)
  ```

</details>
  
I not find control file or DEBIAN/debian folder. Where files stored and what use dist for build?

**Comment by lhhel9l3** [comment]
Yes, I have the same error:

```
Startup error
XAL Authentication library failed to load. Error: Error: node-loader:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.BzvP8w)
/opt/Greenlight/resources/app.asar/app/background.js[constructor()] Starting Greenlight v2.0.0-beta11
```
