### ISSUE TITLE
Beta 9/10 -- Connection Issue: Error fetching consoles. Status: 401

### ISSUE THREAD

**Issue by jshessen** [unknownskl/xbox-xcloud-client#895]
I am currently on Linux, and I am getting the same type of response on Beta 9 (after clearing my data):

```
$ ./Greenlight-2.0.0-beta9.AppImage 
/tmp/.mount_Greenlrbpag3/resources/app.asar/app/background.js[constructor()] Starting Greenlight v2.0.0-beta9
events.ts: Retrieved xuid: { xuid: '2801346196799550', state: 'Offline', cloaked: true }
[jshessen@unity Greenlight] $ ./Greenlight-2.0.0-beta9.AppImage 
/tmp/.mount_GreenlQItsEb/resources/app.asar/app/background.js[constructor()] Starting Greenlight v2.0.0-beta9
events.ts: Retrieved xuid: { xuid: '2801346196799550', state: 'Offline', cloaked: true }
Error fetching consoles. Status: 401 Body: 
(node:283821) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'code')
    at /tmp/.mount_GreenlQItsEb/resources/app.asar/app/background.js:1:91979
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `greenlight --trace-warnings ...` to show where the warning was created)
(node:283821) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

**Comment by jshessen** [comment]
Using Beta 10 -- after logging out, and clearing data, the following is written to the command prompt after attempting login:

```
$ ./Greenlight-2.0.0-beta10.AppImage 
/tmp/.mount_GreenlGSGnlz/resources/app.asar/app/background.js[constructor()] Starting Greenlight v2.0.0-beta10
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }', src/rs_xal_authenticator.rs:236:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(node:483396) UnhandledPromiseRejectionWarning: Error: sending on a closed channel
    at XalAuthenticator.close (/tmp/.mount_GreenlGSGnlz/resources/app.asar/app/background.js:1:682)
    at BrowserWindow.<anonymous> (/tmp/.mount_GreenlGSGnlz/resources/app.asar/app/background.js:1:98890)
    at BrowserWindow.emit (node:events:539:35)
    at /tmp/.mount_GreenlGSGnlz/resources/app.asar/app/background.js:1:100403
(Use `greenlight --trace-warnings ...` to show where the warning was created)
(node:483396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
After terminating the command and relaunching, it progresses past the login, but hangs in the "We are getting your stream ready..."

````
$ ./Greenlight-2.0.0-beta10.AppImage 
/tmp/.mount_GreenlqVpknC/resources/app.asar/app/background.js[constructor()] Starting Greenlight v2.0.0-beta10
events.ts: Retrieved xuid: { xuid: '2801346196799550', state: 'Offline', cloaked: true }
Error fetching consoles. Status: 401 Body: 
(node:483612) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'code')
    at /tmp/.mount_GreenlqVpknC/resources/app.asar/app/background.js:1:91980
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `greenlight --trace-warnings ...` to show where the warning was created)
(node:483612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```


`

**Comment by jshessen** [comment]
Duplicate of #896
